Controllers/HotelController.cs
using Microsoft.AspNetCore.Mvc;

namespace Hotel.Controllers
{
    public class HotelController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Controllers/QuartoController.cs
using System.Collections.Generic;
using System.Linq;
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Hotel.Models;

namespace Hotel.Controllers
{
    public class QuartoController : Controller
    {
        private readonly HotelContext _context;

        public QuartoController(HotelContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            var quartos = from q in _context.Quartos
                                 select q;
            
            return View(quartos);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Numero,CamasCasal,CamasSolteiro,PossuiBanheiro,PossuiInternet,PossuiTv")] Quarto quarto)
        {
            if(ModelState.IsValid)
            {
                _context.Add(quarto);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(quarto);
        }

        public async Task<IActionResult> Edit(int Id)
        {
            var quarto = await _context.Quartos.FindAsync(Id);

            return View(quarto);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Numero,CamasCasal,CamasSolteiro,PossuiBanheiro,PossuiInternet,PossuiTv")] Quarto quarto)
        {
            if(ModelState.IsValid)
            {
                _context.Quartos.Update(quarto);
                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }
            return View(quarto);

        }

        public async Task<IActionResult> Delete(int Id)
        {
            var quarto = await _context.Quartos.FindAsync(Id);

            return View(quarto);
        }

        [HttpPost, Route("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ConfirmDelete(int numero)
        {
            Quarto quarto = await _context.Quartos.FindAsync(numero);

            _context.Quartos.Remove(quarto);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

    }
}

Controllers/RelatorioController.cs
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq;
using System;
using Hotel.Models;

namespace Hotel.Controllers
{
    public class RelatorioController : Controller
    {
        private readonly HotelContext _context;

        public RelatorioController(HotelContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            IEnumerable<decimal> atualMensal = from v in _context.Reservas
                                                where v.DataEntrada.Month == DateTime.Today.Month
                                                select v.ValorPago;

            IEnumerable<decimal> futuroMensal = from v in _context.Reservas
                                                where v.DataEntrada.Month == DateTime.Today.Month
                                                select v.ValorTotal;
            
            IEnumerable<decimal> atualAnual = from v in _context.Reservas
                                                where v.DataEntrada.Year == DateTime.Today.Year
                                                select v.ValorPago;

            IEnumerable<decimal> futuroAnual = from v in _context.Reservas
                                                where v.DataEntrada.Year == DateTime.Today.Year
                                                select v.ValorTotal;

            RelatorioModelView relatorio = new RelatorioModelView()
            {
                ValorAtualMensal = atualMensal.Sum(),
                ValorFuturoMensal = futuroMensal.Sum(),
                ValorAtualAnual = atualAnual.Sum(),
                ValorFuturoAnual = futuroAnual.Sum()
            };

            return View(relatorio);

        }
    }

}

Controllers/ValoresController.cs
using Microsoft.AspNetCore.Mvc;
using Hotel.Models;
using System.Linq;
using System.Threading.Tasks;

namespace Hotel.Controllers
{
    public class ValoresController : Controller
    {
        private readonly HotelContext _context;
        private readonly ValoresService _pricing;

        public ValoresController(HotelContext context, ValoresService valores)
        {
            _context = context;
            _pricing = valores;
        }

        public async Task<IActionResult> Index()
        {
            var valores = await _pricing.getValues();

            return View(valores);
        }

        [HttpPost]
        public async Task<IActionResult> Alterar(Valores valores)
        {
            await _pricing.setValues(valores);
            
            return RedirectToAction(nameof(Index), "Hotel");
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Hotel</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Hotel" asp-action="Index">Hotel</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Hotel" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Reserva" asp-action="Index">Reservas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Quarto" asp-action="Index">Quartos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Valores" asp-action="Index">Preços</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Relatorio" asp-action="Index">Relatorio</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Hotel - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>